DROP TABLE IF EXISTS bounties;
CREATE TABLE bounties(
	id SERIAL8 PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	species VARCHAR(255) NOT NULL,
	fav_weapon VARCHAR(255) NOT NULL,
	value SMALLINT NOT NULL
);
